### PR TITLE
Create correct_swap_sign.R

### PR DESCRIPTION
**Pull request by AshwinAgrawal16**
Hi,
This pull request is in accordance with the issue #23 (use case: data cleaning paper using GBIF data). I have created a function which will check any switched latitude and longitude and also any sign confusion between the two.

In the suggested function first I download country information from the natural-earth data, then I check for valid location, swapped coordinates and any sign changes. The above function only solves part of the issue, I will also solve remaining part in near future.

Please review the code and if there are any errors or any further requirements please let me know.

Regards
Ashwin

### CODE REVIEW

**Comment by sckott** [comment]
hi @AshwinAgrawal16 thanks for this. 

These kinds of things don't go in `R/`, but rather as a vignette or possibly in demos http://r-pkgs.had.co.nz/misc.html - problem with that is we'd still need to have those pkgs in `Suggests` - for now, please put it in `inst/examples` - you can just add changes to this PR

**Comment by AshwinAgrawal16** [comment]
Sorry for the inconvenience caused. I have moved the file to inst/examples.
If there are any further changes requested please let me know.

Regards
Ashwin

**Comment by AshwinAgrawal16** [comment]
I have coded a pipeline to test all the three functions (checkLocation, correctSign and correctSwap) in the PR. Should I code separate tests for each function or a common pipeline will suffice.

Regards
Ashwin

**Comment by sckott** [comment]
what do you mean by 

> I have coded a pipeline to test all the three functions

**Comment by sckott** [comment]
@AshwinAgrawal16 thoughts?

**Comment by AshwinAgrawal16** [comment]
Sorry, for late reply. I was kind of busy. I will make this PR  merge able as soon as possible. In this I will set up three functions:
1. Location check- To check whether the location is valid or not.
2. Check sign- To check the sign of the coordinates.
3. Check swap- To check the swap of the coordinates.

After applying the 2 and 3 functions I will check the result through the location check (1st function)  to check whether modified location is valid.

Apologies for late response.

**Comment by sckott** [comment]
@AshwinAgrawal16 do you still intend to finish this?

**Comment by sckott** [comment]
Any thoughts @AshwinAgrawal16  ?

**Pull request closed without merging**
